apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: foo-backendconfig
spec:
  timeoutSec: 43200  
  connectionDraining:
    drainingTimeoutSec: 60  
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 5
    requestPath: /healthz
    port: 8080
